# Site settings
title: CSIT 2230
email: bstrdsmkr@gmail.com
description: "My portfolio site for Dr. Brown's CSIT 2230 class at Pellissippi State"
baseurl: /CSIT2230
url: "bstrdsmkr.github.io"
github_username:  Bstrdsmkr

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
